/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sohail.alam.quizing_app;

/**
 *
 * @author sohail.alam
 */
public class QuizingApp extends javax.swing.JFrame {

	/**
	 * Creates new form QuizingApp
	 */
	public QuizingApp() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTextField1 = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jTabbedPane_quiziingApp = new javax.swing.JTabbedPane();
                jPanel_userAccess = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel_userLogin = new javax.swing.JLabel();
                jLabel_username = new javax.swing.JLabel();
                jTextField_username = new javax.swing.JTextField();
                jLabel_password = new javax.swing.JLabel();
                jToggleButton_login = new javax.swing.JToggleButton();
                jLabel_userAccessStatus = new javax.swing.JLabel();
                jPasswordField_password = new javax.swing.JPasswordField();
                jPanel_manageQuiz = new javax.swing.JPanel();
                jTabbedPane_manageQuiz = new javax.swing.JTabbedPane();
                jPanel_createQuiz = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                jSplitPane_CreateQuiz = new javax.swing.JSplitPane();
                jPanel6 = new javax.swing.JPanel();
                jLabel_createQuizSubject = new javax.swing.JLabel();
                jTextField_createQuizSubject = new javax.swing.JTextField();
                jLabel_chapterOrTopic = new javax.swing.JLabel();
                jTextField_chapterOrTopic = new javax.swing.JTextField();
                jButton_addQuestion = new javax.swing.JButton();
                jButton_addOption = new javax.swing.JButton();
                jLabel_totalQuestions = new javax.swing.JLabel();
                jTextField_totalQuestions = new javax.swing.JTextField();
                jLabel_setTimeLimit = new javax.swing.JLabel();
                jTextField_setTimeLimit = new javax.swing.JTextField();
                jButton_submitQuiz = new javax.swing.JButton();
                jPanel7 = new javax.swing.JPanel();
                jLabel_questionOrOption = new javax.swing.JLabel();
                jButton_selectImage = new javax.swing.JButton();
                jPanel8 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea_createQuizQuestion = new javax.swing.JTextArea();
                jCheckBox_createQuizSelectCorrectAnswer = new javax.swing.JCheckBox();
                jPanel_viewQuiz = new javax.swing.JPanel();
                jPanel9 = new javax.swing.JPanel();
                jPanel10 = new javax.swing.JPanel();
                jLabel_viewQuizSelectSubject = new javax.swing.JLabel();
                jComboBox_viewQuizSelectSubject = new javax.swing.JComboBox();
                jLabel_viewQuizSelectTopic = new javax.swing.JLabel();
                jComboBox_viewQuizSelectTopic = new javax.swing.JComboBox();
                jComboBox_viewQuizSelectQuiz = new javax.swing.JComboBox();
                jLabel_viewQuizSelectQuiz = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jLabel_viewQuizQSolved = new javax.swing.JLabel();
                jTextField__viewQuizQSolved = new javax.swing.JTextField();
                jLabel_viewQuizTimeLeft = new javax.swing.JLabel();
                jTextField_viewQuizTimeLeft = new javax.swing.JTextField();
                jSplitPane1 = new javax.swing.JSplitPane();
                jPanel11 = new javax.swing.JPanel();
                jLabel_viewQuizQuestion = new javax.swing.JLabel();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTextArea_viewQuizQuestion = new javax.swing.JTextArea();
                jLabel_viewQuizQNo = new javax.swing.JLabel();
                jPanel12 = new javax.swing.JPanel();
                jPanel13 = new javax.swing.JPanel();
                jScrollPane4 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jButton_viewQuizClear = new javax.swing.JButton();
                jButton_viewQuizSubmit = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jPanel_viewScores = new javax.swing.JPanel();
                jPanel14 = new javax.swing.JPanel();
                jLabel_viewQuizSelectSubject1 = new javax.swing.JLabel();
                jComboBox_viewQuizSelectSubject1 = new javax.swing.JComboBox();
                jLabel_viewQuizSelectTopic1 = new javax.swing.JLabel();
                jComboBox_viewQuizSelectTopic1 = new javax.swing.JComboBox();
                jComboBox_viewQuizSelectQuiz1 = new javax.swing.JComboBox();
                jLabel_viewQuizSelectQuiz1 = new javax.swing.JLabel();
                jPanel15 = new javax.swing.JPanel();
                jButton_viewScoreClearList = new javax.swing.JButton();
                jButton_viewScoreSaveList = new javax.swing.JButton();
                jScrollPane5 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();

                java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/sohail/alam/quizing_app/Bundle"); // NOI18N
                jTextField1.setText(bundle.getString("QuizingApp.jTextField1.text")); // NOI18N

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle(bundle.getString("QuizingApp.title")); // NOI18N
                setAlwaysOnTop(true);
                setMaximumSize(new java.awt.Dimension(800, 500));
                setMinimumSize(new java.awt.Dimension(800, 500));
                setResizable(false);

                jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

                jLabel1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 0, 255));
                jLabel1.setText(bundle.getString("QuizingApp.jLabel1.text")); // NOI18N

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(352, 352, 352)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

                jTabbedPane_quiziingApp.setMaximumSize(new java.awt.Dimension(100, 100));
                jTabbedPane_quiziingApp.setMinimumSize(new java.awt.Dimension(100, 100));

                jPanel_userAccess.setMaximumSize(new java.awt.Dimension(793, 387));
                jPanel_userAccess.setMinimumSize(new java.awt.Dimension(793, 387));

                jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

                jLabel_userLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
                jLabel_userLogin.setText(bundle.getString("QuizingApp.jLabel_userLogin.text")); // NOI18N

                jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel_username.setForeground(new java.awt.Color(204, 0, 0));
                jLabel_username.setText(bundle.getString("QuizingApp.jLabel_username.text")); // NOI18N

                jTextField_username.setText(bundle.getString("QuizingApp.jTextField_username.text")); // NOI18N

                jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabel_password.setForeground(new java.awt.Color(204, 0, 0));
                jLabel_password.setText(bundle.getString("QuizingApp.jLabel_password.text")); // NOI18N

                jToggleButton_login.setBackground(new java.awt.Color(0, 153, 0));
                jToggleButton_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jToggleButton_login.setText(bundle.getString("QuizingApp.jToggleButton_login.text")); // NOI18N

                jLabel_userAccessStatus.setText(bundle.getString("QuizingApp.jLabel_userAccessStatus.text")); // NOI18N

                jPasswordField_password.setText(bundle.getString("QuizingApp.jPasswordField_password.text")); // NOI18N

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGap(159, 159, 159)
                                                                .addComponent(jLabel_userLogin))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel_username)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel_userAccessStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jToggleButton_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel_password))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addComponent(jPasswordField_password))))
                                .addContainerGap())
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_userLogin)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel_username)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel_password)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_userAccessStatus)
                                .addContainerGap(18, Short.MAX_VALUE))
                );

                jTextField_username.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jTextField_username.AccessibleContext.accessibleName")); // NOI18N

                javax.swing.GroupLayout jPanel_userAccessLayout = new javax.swing.GroupLayout(jPanel_userAccess);
                jPanel_userAccess.setLayout(jPanel_userAccessLayout);
                jPanel_userAccessLayout.setHorizontalGroup(
                        jPanel_userAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_userAccessLayout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200))
                );
                jPanel_userAccessLayout.setVerticalGroup(
                        jPanel_userAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_userAccessLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                );

                jTabbedPane_quiziingApp.addTab(bundle.getString("QuizingApp.jPanel_userAccess.TabConstraints.tabTitle"), jPanel_userAccess); // NOI18N
                jPanel_userAccess.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jPanel_userAccess.AccessibleContext.accessibleName")); // NOI18N

                jPanel_manageQuiz.setMaximumSize(new java.awt.Dimension(793, 409));
                jPanel_manageQuiz.setMinimumSize(new java.awt.Dimension(793, 409));

                jTabbedPane_manageQuiz.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
                jTabbedPane_manageQuiz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jTabbedPane_manageQuiz.setMaximumSize(new java.awt.Dimension(100, 100));
                jTabbedPane_manageQuiz.setMinimumSize(new java.awt.Dimension(100, 100));

                jSplitPane_CreateQuiz.setDividerLocation(200);

                jLabel_createQuizSubject.setText(bundle.getString("QuizingApp.jLabel_createQuizSubject.text")); // NOI18N

                jTextField_createQuizSubject.setText(bundle.getString("QuizingApp.jTextField_createQuizSubject.text")); // NOI18N

                jLabel_chapterOrTopic.setText(bundle.getString("QuizingApp.jLabel_chapterOrTopic.text")); // NOI18N

                jTextField_chapterOrTopic.setText(bundle.getString("QuizingApp.jTextField_chapterOrTopic.text")); // NOI18N

                jButton_addQuestion.setBackground(new java.awt.Color(0, 204, 204));
                jButton_addQuestion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_addQuestion.setText(bundle.getString("QuizingApp.jButton_addQuestion.text")); // NOI18N

                jButton_addOption.setBackground(new java.awt.Color(0, 204, 102));
                jButton_addOption.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_addOption.setText(bundle.getString("QuizingApp.jButton_addOption.text")); // NOI18N

                jLabel_totalQuestions.setText(bundle.getString("QuizingApp.jLabel_totalQuestions.text")); // NOI18N

                jTextField_totalQuestions.setEditable(false);
                jTextField_totalQuestions.setText(bundle.getString("QuizingApp.jTextField_totalQuestions.text")); // NOI18N
                jTextField_totalQuestions.setAutoscrolls(false);

                jLabel_setTimeLimit.setText(bundle.getString("QuizingApp.jLabel_setTimeLimit.text")); // NOI18N

                jTextField_setTimeLimit.setText(bundle.getString("QuizingApp.jTextField_setTimeLimit.text")); // NOI18N

                jButton_submitQuiz.setBackground(new java.awt.Color(255, 51, 51));
                jButton_submitQuiz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_submitQuiz.setText(bundle.getString("QuizingApp.jButton_submitQuiz.text")); // NOI18N

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_submitQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField_createQuizSubject)
                                        .addComponent(jTextField_chapterOrTopic)
                                        .addComponent(jButton_addQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_addOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(jLabel_totalQuestions)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                                .addComponent(jTextField_totalQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_setTimeLimit)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel_createQuizSubject)
                                                        .addComponent(jLabel_chapterOrTopic)
                                                        .addComponent(jLabel_setTimeLimit))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                jPanel6Layout.setVerticalGroup(
                        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_createQuizSubject)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_createQuizSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_chapterOrTopic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_chapterOrTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_setTimeLimit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_setTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_addQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_addOption, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_totalQuestions)
                                        .addComponent(jTextField_totalQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_submitQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE))
                );

                jSplitPane_CreateQuiz.setLeftComponent(jPanel6);

                jLabel_questionOrOption.setText(bundle.getString("QuizingApp.jLabel_questionOrOption.text")); // NOI18N

                jButton_selectImage.setBackground(new java.awt.Color(0, 102, 153));
                jButton_selectImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_selectImage.setText(bundle.getString("QuizingApp.jButton_selectImage.text")); // NOI18N

                jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                );

                jTextArea_createQuizQuestion.setColumns(20);
                jTextArea_createQuizQuestion.setLineWrap(true);
                jTextArea_createQuizQuestion.setRows(5);
                jScrollPane2.setViewportView(jTextArea_createQuizQuestion);

                jCheckBox_createQuizSelectCorrectAnswer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jCheckBox_createQuizSelectCorrectAnswer.setForeground(new java.awt.Color(204, 0, 0));
                jCheckBox_createQuizSelectCorrectAnswer.setText(bundle.getString("QuizingApp.jCheckBox_createQuizSelectCorrectAnswer.text")); // NOI18N

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(jLabel_questionOrOption)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jButton_selectImage, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jCheckBox_createQuizSelectCorrectAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))))
                                .addContainerGap())
                );
                jPanel7Layout.setVerticalGroup(
                        jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_questionOrOption)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton_selectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox_createQuizSelectCorrectAnswer))
                                .addContainerGap(12, Short.MAX_VALUE))
                );

                jSplitPane_CreateQuiz.setRightComponent(jPanel7);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane_CreateQuiz)
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane_CreateQuiz)
                );

                javax.swing.GroupLayout jPanel_createQuizLayout = new javax.swing.GroupLayout(jPanel_createQuiz);
                jPanel_createQuiz.setLayout(jPanel_createQuizLayout);
                jPanel_createQuizLayout.setHorizontalGroup(
                        jPanel_createQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel_createQuizLayout.setVerticalGroup(
                        jPanel_createQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane_manageQuiz.addTab(bundle.getString("QuizingApp.jPanel_createQuiz.TabConstraints.tabTitle"), jPanel_createQuiz); // NOI18N

                jLabel_viewQuizSelectSubject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel_viewQuizSelectSubject.setForeground(new java.awt.Color(0, 102, 204));
                jLabel_viewQuizSelectSubject.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectSubject.text")); // NOI18N

                jComboBox_viewQuizSelectSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabel_viewQuizSelectTopic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel_viewQuizSelectTopic.setForeground(new java.awt.Color(0, 102, 204));
                jLabel_viewQuizSelectTopic.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectTopic.text")); // NOI18N

                jComboBox_viewQuizSelectTopic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jComboBox_viewQuizSelectQuiz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabel_viewQuizSelectQuiz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel_viewQuizSelectQuiz.setForeground(new java.awt.Color(0, 102, 204));
                jLabel_viewQuizSelectQuiz.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectQuiz.text")); // NOI18N

                jLabel_viewQuizQSolved.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jLabel_viewQuizQSolved.setForeground(new java.awt.Color(204, 0, 0));
                jLabel_viewQuizQSolved.setText(bundle.getString("QuizingApp.jLabel_viewQuizQSolved.text")); // NOI18N

                jTextField__viewQuizQSolved.setEditable(false);
                jTextField__viewQuizQSolved.setText(bundle.getString("QuizingApp.jTextField__viewQuizQSolved.text")); // NOI18N

                jLabel_viewQuizTimeLeft.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jLabel_viewQuizTimeLeft.setForeground(new java.awt.Color(204, 0, 0));
                jLabel_viewQuizTimeLeft.setText(bundle.getString("QuizingApp.jLabel_viewQuizTimeLeft.text")); // NOI18N

                jTextField_viewQuizTimeLeft.setEditable(false);
                jTextField_viewQuizTimeLeft.setText(bundle.getString("QuizingApp.jTextField_viewQuizTimeLeft.text")); // NOI18N

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_viewQuizQSolved)
                                        .addComponent(jLabel_viewQuizTimeLeft))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_viewQuizTimeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jTextField__viewQuizQSolved))
                                .addContainerGap())
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField__viewQuizQSolved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_viewQuizQSolved))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_viewQuizTimeLeft)
                                        .addComponent(jTextField_viewQuizTimeLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
                jPanel10.setLayout(jPanel10Layout);
                jPanel10Layout.setHorizontalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_viewQuizSelectSubject)
                                        .addComponent(jComboBox_viewQuizSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_viewQuizSelectTopic)
                                        .addComponent(jComboBox_viewQuizSelectTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_viewQuizSelectQuiz)
                                        .addComponent(jComboBox_viewQuizSelectQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel10Layout.setVerticalGroup(
                        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel_viewQuizSelectSubject)
                                                        .addComponent(jLabel_viewQuizSelectTopic)
                                                        .addComponent(jLabel_viewQuizSelectQuiz))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jComboBox_viewQuizSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox_viewQuizSelectTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox_viewQuizSelectQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7))
                );

                jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_viewQuizSelectQuiz, jComboBox_viewQuizSelectSubject, jComboBox_viewQuizSelectTopic});

                jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                jSplitPane1.setDividerLocation(200);

                jLabel_viewQuizQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel_viewQuizQuestion.setForeground(new java.awt.Color(0, 153, 51));
                jLabel_viewQuizQuestion.setText(bundle.getString("QuizingApp.jLabel_viewQuizQuestion.text")); // NOI18N

                jTextArea_viewQuizQuestion.setColumns(20);
                jTextArea_viewQuizQuestion.setLineWrap(true);
                jTextArea_viewQuizQuestion.setRows(5);
                jScrollPane3.setViewportView(jTextArea_viewQuizQuestion);

                jLabel_viewQuizQNo.setText(bundle.getString("QuizingApp.jLabel_viewQuizQNo.text")); // NOI18N

                javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
                jPanel11.setLayout(jPanel11Layout);
                jPanel11Layout.setHorizontalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3)
                                        .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addComponent(jLabel_viewQuizQuestion)
                                                .addGap(18, 18, Short.MAX_VALUE)
                                                .addComponent(jLabel_viewQuizQNo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24))
                );
                jPanel11Layout.setVerticalGroup(
                        jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel11Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_viewQuizQuestion)
                                        .addComponent(jLabel_viewQuizQNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                .addContainerGap())
                );

                jSplitPane1.setLeftComponent(jPanel11);

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane4.setViewportView(jTable1);

                javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
                jPanel13.setLayout(jPanel13Layout);
                jPanel13Layout.setHorizontalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                );
                jPanel13Layout.setVerticalGroup(
                        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                );

                jButton_viewQuizClear.setBackground(new java.awt.Color(255, 51, 51));
                jButton_viewQuizClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_viewQuizClear.setText(bundle.getString("QuizingApp.jButton_viewQuizClear.text")); // NOI18N

                jButton_viewQuizSubmit.setBackground(new java.awt.Color(0, 204, 102));
                jButton_viewQuizSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_viewQuizSubmit.setText(bundle.getString("QuizingApp.jButton_viewQuizSubmit.text")); // NOI18N

                jButton2.setBackground(new java.awt.Color(0, 102, 204));
                jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton2.setText(bundle.getString("QuizingApp.jButton2.text")); // NOI18N

                javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
                jPanel12.setLayout(jPanel12Layout);
                jPanel12Layout.setHorizontalGroup(
                        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_viewQuizClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(jButton_viewQuizSubmit)
                                .addContainerGap())
                );

                jPanel12Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton_viewQuizClear, jButton_viewQuizSubmit});

                jPanel12Layout.setVerticalGroup(
                        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton_viewQuizClear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton_viewQuizSubmit))
                                .addContainerGap())
                );

                jPanel12Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton_viewQuizClear, jButton_viewQuizSubmit});

                jSplitPane1.setRightComponent(jPanel12);

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                );
                jPanel9Layout.setVerticalGroup(
                        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSplitPane1)
                                .addContainerGap())
                );

                javax.swing.GroupLayout jPanel_viewQuizLayout = new javax.swing.GroupLayout(jPanel_viewQuiz);
                jPanel_viewQuiz.setLayout(jPanel_viewQuizLayout);
                jPanel_viewQuizLayout.setHorizontalGroup(
                        jPanel_viewQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel_viewQuizLayout.setVerticalGroup(
                        jPanel_viewQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jTabbedPane_manageQuiz.addTab(bundle.getString("QuizingApp.jPanel_viewQuiz.TabConstraints.tabTitle"), jPanel_viewQuiz); // NOI18N

                jLabel_viewQuizSelectSubject1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel_viewQuizSelectSubject1.setForeground(new java.awt.Color(204, 0, 0));
                jLabel_viewQuizSelectSubject1.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectSubject1.text")); // NOI18N

                jComboBox_viewQuizSelectSubject1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabel_viewQuizSelectTopic1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel_viewQuizSelectTopic1.setForeground(new java.awt.Color(204, 0, 0));
                jLabel_viewQuizSelectTopic1.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectTopic1.text")); // NOI18N

                jComboBox_viewQuizSelectTopic1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jComboBox_viewQuizSelectQuiz1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                jLabel_viewQuizSelectQuiz1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel_viewQuizSelectQuiz1.setForeground(new java.awt.Color(204, 0, 0));
                jLabel_viewQuizSelectQuiz1.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectQuiz1.text")); // NOI18N

                javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
                jPanel14.setLayout(jPanel14Layout);
                jPanel14Layout.setHorizontalGroup(
                        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox_viewQuizSelectSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel_viewQuizSelectSubject1))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_viewQuizSelectTopic1)
                                        .addComponent(jComboBox_viewQuizSelectTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_viewQuizSelectQuiz1)
                                        .addComponent(jComboBox_viewQuizSelectQuiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel14Layout.setVerticalGroup(
                        jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel_viewQuizSelectSubject1)
                                        .addComponent(jLabel_viewQuizSelectTopic1)
                                        .addComponent(jLabel_viewQuizSelectQuiz1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBox_viewQuizSelectTopic1)
                                        .addGroup(jPanel14Layout.createSequentialGroup()
                                                .addComponent(jComboBox_viewQuizSelectSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jComboBox_viewQuizSelectQuiz1))
                                .addContainerGap())
                );

                jButton_viewScoreClearList.setBackground(new java.awt.Color(0, 153, 204));
                jButton_viewScoreClearList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_viewScoreClearList.setText(bundle.getString("QuizingApp.jButton_viewScoreClearList.text")); // NOI18N

                jButton_viewScoreSaveList.setBackground(new java.awt.Color(0, 204, 102));
                jButton_viewScoreSaveList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
                jButton_viewScoreSaveList.setText(bundle.getString("QuizingApp.jButton_viewScoreSaveList.text")); // NOI18N

                javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
                jPanel15.setLayout(jPanel15Layout);
                jPanel15Layout.setHorizontalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_viewScoreClearList, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_viewScoreSaveList)
                                .addContainerGap())
                );

                jPanel15Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_viewScoreClearList, jButton_viewScoreSaveList});

                jPanel15Layout.setVerticalGroup(
                        jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton_viewScoreClearList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_viewScoreSaveList))
                );

                jPanel15Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_viewScoreClearList, jButton_viewScoreSaveList});

                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane5.setViewportView(jTable2);

                javax.swing.GroupLayout jPanel_viewScoresLayout = new javax.swing.GroupLayout(jPanel_viewScores);
                jPanel_viewScores.setLayout(jPanel_viewScoresLayout);
                jPanel_viewScoresLayout.setHorizontalGroup(
                        jPanel_viewScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                        .addComponent(jScrollPane5)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_viewScoresLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel_viewScoresLayout.setVerticalGroup(
                        jPanel_viewScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_viewScoresLayout.createSequentialGroup()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                jTabbedPane_manageQuiz.addTab(bundle.getString("QuizingApp.jPanel_viewScores.TabConstraints.tabTitle"), jPanel_viewScores); // NOI18N

                javax.swing.GroupLayout jPanel_manageQuizLayout = new javax.swing.GroupLayout(jPanel_manageQuiz);
                jPanel_manageQuiz.setLayout(jPanel_manageQuizLayout);
                jPanel_manageQuizLayout.setHorizontalGroup(
                        jPanel_manageQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_manageQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                jPanel_manageQuizLayout.setVerticalGroup(
                        jPanel_manageQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_manageQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                jTabbedPane_quiziingApp.addTab(bundle.getString("QuizingApp.jPanel_manageQuiz.TabConstraints.tabTitle"), jPanel_manageQuiz); // NOI18N
                jPanel_manageQuiz.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jPanel_manageQuiz.AccessibleContext.accessibleName")); // NOI18N

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_quiziingApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane_quiziingApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                jTabbedPane_quiziingApp.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jTabbedPane_quiziingApp.AccessibleContext.accessibleName")); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new QuizingApp().setVisible(true);
			}
		});
	}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton_addOption;
        private javax.swing.JButton jButton_addQuestion;
        private javax.swing.JButton jButton_selectImage;
        private javax.swing.JButton jButton_submitQuiz;
        private javax.swing.JButton jButton_viewQuizClear;
        private javax.swing.JButton jButton_viewQuizSubmit;
        private javax.swing.JButton jButton_viewScoreClearList;
        private javax.swing.JButton jButton_viewScoreSaveList;
        private javax.swing.JCheckBox jCheckBox_createQuizSelectCorrectAnswer;
        private javax.swing.JComboBox jComboBox_viewQuizSelectQuiz;
        private javax.swing.JComboBox jComboBox_viewQuizSelectQuiz1;
        private javax.swing.JComboBox jComboBox_viewQuizSelectSubject;
        private javax.swing.JComboBox jComboBox_viewQuizSelectSubject1;
        private javax.swing.JComboBox jComboBox_viewQuizSelectTopic;
        private javax.swing.JComboBox jComboBox_viewQuizSelectTopic1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel_chapterOrTopic;
        private javax.swing.JLabel jLabel_createQuizSubject;
        private javax.swing.JLabel jLabel_password;
        private javax.swing.JLabel jLabel_questionOrOption;
        private javax.swing.JLabel jLabel_setTimeLimit;
        private javax.swing.JLabel jLabel_totalQuestions;
        private javax.swing.JLabel jLabel_userAccessStatus;
        private javax.swing.JLabel jLabel_userLogin;
        private javax.swing.JLabel jLabel_username;
        private javax.swing.JLabel jLabel_viewQuizQNo;
        private javax.swing.JLabel jLabel_viewQuizQSolved;
        private javax.swing.JLabel jLabel_viewQuizQuestion;
        private javax.swing.JLabel jLabel_viewQuizSelectQuiz;
        private javax.swing.JLabel jLabel_viewQuizSelectQuiz1;
        private javax.swing.JLabel jLabel_viewQuizSelectSubject;
        private javax.swing.JLabel jLabel_viewQuizSelectSubject1;
        private javax.swing.JLabel jLabel_viewQuizSelectTopic;
        private javax.swing.JLabel jLabel_viewQuizSelectTopic1;
        private javax.swing.JLabel jLabel_viewQuizTimeLeft;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel10;
        private javax.swing.JPanel jPanel11;
        private javax.swing.JPanel jPanel12;
        private javax.swing.JPanel jPanel13;
        private javax.swing.JPanel jPanel14;
        private javax.swing.JPanel jPanel15;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JPanel jPanel_createQuiz;
        private javax.swing.JPanel jPanel_manageQuiz;
        private javax.swing.JPanel jPanel_userAccess;
        private javax.swing.JPanel jPanel_viewQuiz;
        private javax.swing.JPanel jPanel_viewScores;
        private javax.swing.JPasswordField jPasswordField_password;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JSplitPane jSplitPane1;
        private javax.swing.JSplitPane jSplitPane_CreateQuiz;
        private javax.swing.JTabbedPane jTabbedPane_manageQuiz;
        private javax.swing.JTabbedPane jTabbedPane_quiziingApp;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTextArea jTextArea_createQuizQuestion;
        private javax.swing.JTextArea jTextArea_viewQuizQuestion;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField__viewQuizQSolved;
        private javax.swing.JTextField jTextField_chapterOrTopic;
        private javax.swing.JTextField jTextField_createQuizSubject;
        private javax.swing.JTextField jTextField_setTimeLimit;
        private javax.swing.JTextField jTextField_totalQuestions;
        private javax.swing.JTextField jTextField_username;
        private javax.swing.JTextField jTextField_viewQuizTimeLeft;
        private javax.swing.JToggleButton jToggleButton_login;
        // End of variables declaration//GEN-END:variables
}
