/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sohail.alam.quizing_app;

import java.awt.Color;

/**
 *
 * @author sohail.alam
 */
public class QuizingApp extends javax.swing.JFrame {

    private boolean isLoggedIn = false;
    private int currentQuestionNumber = 0;
    private int previousQuestionNumber = 0;
    private int nextQuestionNumber = 0;
    private String quizSubject = null;
    private String quizTopic = null;
    private String quizTimeLimit = null;
    private Quiz quiz = Quiz.getInstance();
    private Questions[] questions = new Questions[100]; // questions[question_number]
    private Options[][] options = null; // options[question_number][option_number]
    private QuizingAppMethods methods = QuizingAppMethods.getInstance();

    /**
     * Creates new form QuizingApp
     */
    public QuizingApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_header = new javax.swing.JPanel();
        jLabel_header = new javax.swing.JLabel();
        jPanel_content = new javax.swing.JPanel();
        jTabbedPane_quiziingApp = new javax.swing.JTabbedPane();
        jPanel_userAccess = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_userLogin = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel_password = new javax.swing.JLabel();
        jToggleButton_login = new javax.swing.JToggleButton();
        jLabel_userAccessStatus = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jPanel_manageQuiz = new javax.swing.JPanel();
        jTabbedPane_manageQuiz = new javax.swing.JTabbedPane();
        jPanel_createQuiz = new javax.swing.JPanel();
        jPanel_createQuizContent = new javax.swing.JPanel();
        jSplitPane_CreateQuiz = new javax.swing.JSplitPane();
        jPanel_quizDetails = new javax.swing.JPanel();
        jLabel_createQuizSubject = new javax.swing.JLabel();
        jTextField_createQuizSubject = new javax.swing.JTextField();
        jLabel_chapterOrTopic = new javax.swing.JLabel();
        jTextField_createQuizChapterOrTopic = new javax.swing.JTextField();
        jButton_createQuizAddQuestion = new javax.swing.JButton();
        jButton_createQuizAddOption = new javax.swing.JButton();
        jLabel_totalQuestions = new javax.swing.JLabel();
        jTextField_totalQuestions = new javax.swing.JTextField();
        jLabel_setTimeLimit = new javax.swing.JLabel();
        jTextField_createQuizSetTimeLimit = new javax.swing.JTextField();
        jButton_createQuizSubmitQuiz = new javax.swing.JButton();
        jLabel_createQuizQNo = new javax.swing.JLabel();
        jLabel_createQuizONo = new javax.swing.JLabel();
        jComboBox_createQuizQNo = new javax.swing.JComboBox();
        jComboBox_createQuizONo = new javax.swing.JComboBox();
        jPanel_quizContent = new javax.swing.JPanel();
        jLabel_questionOrOption = new javax.swing.JLabel();
        jButton_selectImage = new javax.swing.JButton();
        jPanel_quizImage = new javax.swing.JPanel();
        jScrollPane_quizImage = new javax.swing.JScrollPane();
        jScrollPane_quizText = new javax.swing.JScrollPane();
        jTextArea_createQuizQuestion = new javax.swing.JTextArea();
        jCheckBox_createQuizSelectCorrectAnswer = new javax.swing.JCheckBox();
        jLabel_createQuizDifficultyLevel = new javax.swing.JLabel();
        jComboBox_createQuizDifficultyLevel = new javax.swing.JComboBox();
        jButton_createQuizSave = new javax.swing.JButton();
        jButton_createQuizPrevious = new javax.swing.JButton();
        jButton_createQuizNext = new javax.swing.JButton();
        jPanel_viewQuiz = new javax.swing.JPanel();
        jPanel_viewQuizContent = new javax.swing.JPanel();
        jPanel_selectQuiz = new javax.swing.JPanel();
        jLabel_viewQuizSelectSubject = new javax.swing.JLabel();
        jComboBox_viewQuizSelectSubject = new javax.swing.JComboBox();
        jLabel_viewQuizSelectTopic = new javax.swing.JLabel();
        jComboBox_viewQuizSelectTopic = new javax.swing.JComboBox();
        jComboBox_viewQuizSelectQuiz = new javax.swing.JComboBox();
        jLabel_viewQuizSelectQuiz = new javax.swing.JLabel();
        jPanel_quizTimer = new javax.swing.JPanel();
        jLabel_viewQuizQSolved = new javax.swing.JLabel();
        jTextField__viewQuizQSolved = new javax.swing.JTextField();
        jLabel_viewQuizTimeLeft = new javax.swing.JLabel();
        jTextField_viewQuizTimeLeft = new javax.swing.JTextField();
        jSplitPane_selectedQuizContent = new javax.swing.JSplitPane();
        jPanel_selectedQuizQuestion = new javax.swing.JPanel();
        jLabel_viewQuizQuestion = new javax.swing.JLabel();
        jScrollPane_selectedQuizQuestion = new javax.swing.JScrollPane();
        jTextArea_viewQuizQuestion = new javax.swing.JTextArea();
        jLabel_viewQuizQNo = new javax.swing.JLabel();
        jPanel_selectedQuizOptions = new javax.swing.JPanel();
        jPanel_selectedQuizOptionsTable = new javax.swing.JPanel();
        jScrollPane_selectedQuizOptions = new javax.swing.JScrollPane();
        jTable_selectedQuizOptions = new javax.swing.JTable();
        jButton_viewQuizClear = new javax.swing.JButton();
        jButton_viewQuizSubmit = new javax.swing.JButton();
        jButton_viewQuizSave = new javax.swing.JButton();
        jButton_viewQuizPrevious = new javax.swing.JButton();
        jButton_viewQuizNext = new javax.swing.JButton();
        jPanel_viewScores = new javax.swing.JPanel();
        jPanel_selectQuizSet = new javax.swing.JPanel();
        jLabel_viewQuizSelectSubject1 = new javax.swing.JLabel();
        jComboBox_viewQuizSelectSubject1 = new javax.swing.JComboBox();
        jLabel_viewQuizSelectTopic1 = new javax.swing.JLabel();
        jComboBox_viewQuizSelectTopic1 = new javax.swing.JComboBox();
        jComboBox_viewQuizSelectQuiz1 = new javax.swing.JComboBox();
        jLabel_viewQuizSelectQuiz1 = new javax.swing.JLabel();
        jPanel_viewScoreButtons = new javax.swing.JPanel();
        jButton_viewScoreClearList = new javax.swing.JButton();
        jButton_viewScoreSaveList = new javax.swing.JButton();
        jScrollPane_viewScoresContent = new javax.swing.JScrollPane();
        jTable_viewScores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/sohail/alam/quizing_app/Bundle"); // NOI18N
        setTitle(bundle.getString("QuizingApp.title")); // NOI18N
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel_header.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel_header.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel_header.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_header.setText(bundle.getString("QuizingApp.jLabel_header.text")); // NOI18N

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel_header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_header, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_content.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jTabbedPane_quiziingApp.setMaximumSize(new java.awt.Dimension(100, 100));
        jTabbedPane_quiziingApp.setMinimumSize(new java.awt.Dimension(100, 100));

        jPanel_userAccess.setMaximumSize(new java.awt.Dimension(793, 387));
        jPanel_userAccess.setMinimumSize(new java.awt.Dimension(793, 387));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel_userLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_userLogin.setText(bundle.getString("QuizingApp.jLabel_userLogin.text")); // NOI18N

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_username.setText(bundle.getString("QuizingApp.jLabel_username.text")); // NOI18N

        jTextField_username.setBackground(new java.awt.Color(204, 255, 204));
        jTextField_username.setText(bundle.getString("QuizingApp.jTextField_username.text")); // NOI18N
        jTextField_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usernameMouseClicked(evt);
            }
        });
        jTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_usernameKeyTyped(evt);
            }
        });

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_password.setText(bundle.getString("QuizingApp.jLabel_password.text")); // NOI18N

        jToggleButton_login.setBackground(java.awt.Color.gray);
        jToggleButton_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton_login.setText(bundle.getString("QuizingApp.jToggleButton_login.text")); // NOI18N
        jToggleButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_loginActionPerformed(evt);
            }
        });
        jToggleButton_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton_loginKeyPressed(evt);
            }
        });

        jLabel_userAccessStatus.setText(bundle.getString("QuizingApp.jLabel_userAccessStatus.text")); // NOI18N

        jPasswordField_password.setBackground(new java.awt.Color(204, 255, 204));
        jPasswordField_password.setText(bundle.getString("QuizingApp.jPasswordField_password.text")); // NOI18N
        jPasswordField_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_passwordMouseClicked(evt);
            }
        });
        jPasswordField_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_passwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel_userLogin))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_username)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_userAccessStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_password))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPasswordField_password))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_userLogin)
                .addGap(13, 13, 13)
                .addComponent(jLabel_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_userAccessStatus)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTextField_username.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jTextField_username.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout jPanel_userAccessLayout = new javax.swing.GroupLayout(jPanel_userAccess);
        jPanel_userAccess.setLayout(jPanel_userAccessLayout);
        jPanel_userAccessLayout.setHorizontalGroup(
            jPanel_userAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userAccessLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel_userAccessLayout.setVerticalGroup(
            jPanel_userAccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userAccessLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jTabbedPane_quiziingApp.addTab(bundle.getString("QuizingApp.jPanel_userAccess.TabConstraints.tabTitle"), jPanel_userAccess); // NOI18N
        jPanel_userAccess.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jPanel_userAccess.AccessibleContext.accessibleName")); // NOI18N

        jPanel_manageQuiz.setMaximumSize(new java.awt.Dimension(793, 409));
        jPanel_manageQuiz.setMinimumSize(new java.awt.Dimension(793, 409));

        jTabbedPane_manageQuiz.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane_manageQuiz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane_manageQuiz.setMaximumSize(new java.awt.Dimension(100, 100));
        jTabbedPane_manageQuiz.setMinimumSize(new java.awt.Dimension(100, 100));

        jSplitPane_CreateQuiz.setDividerLocation(200);
        jSplitPane_CreateQuiz.setEnabled(false);

        jLabel_createQuizSubject.setText(bundle.getString("QuizingApp.jLabel_createQuizSubject.text")); // NOI18N

        jTextField_createQuizSubject.setText(bundle.getString("QuizingApp.jTextField_createQuizSubject.text")); // NOI18N
        jTextField_createQuizSubject.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_createQuizSubjectKeyTyped(evt);
            }
        });

        jLabel_chapterOrTopic.setText(bundle.getString("QuizingApp.jLabel_chapterOrTopic.text")); // NOI18N

        jTextField_createQuizChapterOrTopic.setText(bundle.getString("QuizingApp.jTextField_createQuizChapterOrTopic.text")); // NOI18N
        jTextField_createQuizChapterOrTopic.setEnabled(false);
        jTextField_createQuizChapterOrTopic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_createQuizChapterOrTopicKeyTyped(evt);
            }
        });

        jButton_createQuizAddQuestion.setBackground(new java.awt.Color(0, 204, 204));
        jButton_createQuizAddQuestion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_createQuizAddQuestion.setText(bundle.getString("QuizingApp.jButton_createQuizAddQuestion.text")); // NOI18N
        jButton_createQuizAddQuestion.setEnabled(false);
        jButton_createQuizAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createQuizAddQuestionActionPerformed(evt);
            }
        });

        jButton_createQuizAddOption.setBackground(new java.awt.Color(0, 204, 102));
        jButton_createQuizAddOption.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_createQuizAddOption.setText(bundle.getString("QuizingApp.jButton_createQuizAddOption.text")); // NOI18N
        jButton_createQuizAddOption.setEnabled(false);

        jLabel_totalQuestions.setText(bundle.getString("QuizingApp.jLabel_totalQuestions.text")); // NOI18N

        jTextField_totalQuestions.setEditable(false);
        jTextField_totalQuestions.setText(bundle.getString("QuizingApp.jTextField_totalQuestions.text")); // NOI18N
        jTextField_totalQuestions.setAutoscrolls(false);
        jTextField_totalQuestions.setEnabled(false);
        jTextField_totalQuestions.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_totalQuestionsCaretUpdate(evt);
            }
        });

        jLabel_setTimeLimit.setText(bundle.getString("QuizingApp.jLabel_setTimeLimit.text")); // NOI18N

        jTextField_createQuizSetTimeLimit.setText(bundle.getString("QuizingApp.jTextField_createQuizSetTimeLimit.text")); // NOI18N
        jTextField_createQuizSetTimeLimit.setEnabled(false);
        jTextField_createQuizSetTimeLimit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_createQuizSetTimeLimitKeyTyped(evt);
            }
        });

        jButton_createQuizSubmitQuiz.setBackground(new java.awt.Color(255, 51, 51));
        jButton_createQuizSubmitQuiz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_createQuizSubmitQuiz.setText(bundle.getString("QuizingApp.jButton_createQuizSubmitQuiz.text")); // NOI18N
        jButton_createQuizSubmitQuiz.setEnabled(false);

        jLabel_createQuizQNo.setText(bundle.getString("QuizingApp.jLabel_createQuizQNo.text")); // NOI18N

        jLabel_createQuizONo.setText(bundle.getString("QuizingApp.jLabel_createQuizONo.text")); // NOI18N

        jComboBox_createQuizQNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox_createQuizQNo.setEnabled(false);
        jComboBox_createQuizQNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_createQuizQNoActionPerformed(evt);
            }
        });

        jComboBox_createQuizONo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jComboBox_createQuizONo.setEnabled(false);

        javax.swing.GroupLayout jPanel_quizDetailsLayout = new javax.swing.GroupLayout(jPanel_quizDetails);
        jPanel_quizDetails.setLayout(jPanel_quizDetailsLayout);
        jPanel_quizDetailsLayout.setHorizontalGroup(
            jPanel_quizDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_quizDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_quizDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_createQuizSubmitQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_createQuizSubject)
                    .addComponent(jTextField_createQuizChapterOrTopic)
                    .addComponent(jButton_createQuizAddQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_createQuizAddOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_quizDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel_totalQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jTextField_totalQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_createQuizSetTimeLimit)
                    .addGroup(jPanel_quizDetailsLayout.createSequentialGroup()
                        .addGroup(jPanel_quizDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_createQuizSubject)
                            .addComponent(jLabel_chapterOrTopic)
                            .addComponent(jLabel_setTimeLimit))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_quizDetailsLayout.createSequentialGroup()
                        .addComponent(jLabel_createQuizQNo)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_createQuizQNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_createQuizONo)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_createQuizONo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel_quizDetailsLayout.setVerticalGroup(
            jPanel_quizDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_quizDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_createQuizSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_createQuizSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_chapterOrTopic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_createQuizChapterOrTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_setTimeLimit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_createQuizSetTimeLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_createQuizAddQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_createQuizAddOption, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_quizDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_totalQuestions)
                    .addComponent(jTextField_totalQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton_createQuizSubmitQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_quizDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_createQuizQNo)
                    .addComponent(jComboBox_createQuizQNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_createQuizONo)
                    .addComponent(jComboBox_createQuizONo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jSplitPane_CreateQuiz.setLeftComponent(jPanel_quizDetails);

        jLabel_questionOrOption.setText(bundle.getString("QuizingApp.jLabel_questionOrOption.text")); // NOI18N

        jButton_selectImage.setBackground(new java.awt.Color(0, 102, 153));
        jButton_selectImage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_selectImage.setText(bundle.getString("QuizingApp.jButton_selectImage.text")); // NOI18N
        jButton_selectImage.setEnabled(false);

        jPanel_quizImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel_quizImageLayout = new javax.swing.GroupLayout(jPanel_quizImage);
        jPanel_quizImage.setLayout(jPanel_quizImageLayout);
        jPanel_quizImageLayout.setHorizontalGroup(
            jPanel_quizImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_quizImage)
        );
        jPanel_quizImageLayout.setVerticalGroup(
            jPanel_quizImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_quizImage)
        );

        jTextArea_createQuizQuestion.setColumns(20);
        jTextArea_createQuizQuestion.setLineWrap(true);
        jTextArea_createQuizQuestion.setRows(5);
        jTextArea_createQuizQuestion.setEnabled(false);
        jTextArea_createQuizQuestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_createQuizQuestionKeyTyped(evt);
            }
        });
        jScrollPane_quizText.setViewportView(jTextArea_createQuizQuestion);

        jCheckBox_createQuizSelectCorrectAnswer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox_createQuizSelectCorrectAnswer.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBox_createQuizSelectCorrectAnswer.setText(bundle.getString("QuizingApp.jCheckBox_createQuizSelectCorrectAnswer.text")); // NOI18N
        jCheckBox_createQuizSelectCorrectAnswer.setEnabled(false);

        jLabel_createQuizDifficultyLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_createQuizDifficultyLevel.setForeground(new java.awt.Color(51, 153, 0));
        jLabel_createQuizDifficultyLevel.setText(bundle.getString("QuizingApp.jLabel_createQuizDifficultyLevel.text")); // NOI18N

        jComboBox_createQuizDifficultyLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5" }));
        jComboBox_createQuizDifficultyLevel.setEnabled(false);

        jButton_createQuizSave.setBackground(new java.awt.Color(204, 51, 0));
        jButton_createQuizSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_createQuizSave.setText(bundle.getString("QuizingApp.jButton_createQuizSave.text")); // NOI18N
        jButton_createQuizSave.setEnabled(false);
        jButton_createQuizSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createQuizSaveActionPerformed(evt);
            }
        });

        jButton_createQuizPrevious.setBackground(new java.awt.Color(102, 102, 102));
        jButton_createQuizPrevious.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_createQuizPrevious.setText(bundle.getString("QuizingApp.jButton_createQuizPrevious.text")); // NOI18N
        jButton_createQuizPrevious.setEnabled(false);
        jButton_createQuizPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createQuizPreviousActionPerformed(evt);
            }
        });

        jButton_createQuizNext.setBackground(new java.awt.Color(102, 102, 102));
        jButton_createQuizNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton_createQuizNext.setText(bundle.getString("QuizingApp.jButton_createQuizNext.text")); // NOI18N
        jButton_createQuizNext.setEnabled(false);
        jButton_createQuizNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_createQuizNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_quizContentLayout = new javax.swing.GroupLayout(jPanel_quizContent);
        jPanel_quizContent.setLayout(jPanel_quizContentLayout);
        jPanel_quizContentLayout.setHorizontalGroup(
            jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                        .addComponent(jLabel_questionOrOption)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                        .addGroup(jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane_quizText, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                                .addComponent(jButton_createQuizPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_createQuizSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_createQuizNext, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_quizImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox_createQuizSelectCorrectAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_quizContentLayout.createSequentialGroup()
                                .addComponent(jLabel_createQuizDifficultyLevel)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_createQuizDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_selectImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel_quizContentLayout.setVerticalGroup(
            jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_questionOrOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                        .addComponent(jPanel_quizImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_selectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane_quizText, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jCheckBox_createQuizSelectCorrectAnswer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_createQuizDifficultyLevel)
                            .addComponent(jComboBox_createQuizDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_quizContentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_quizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_createQuizPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_createQuizSave, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_createQuizNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane_CreateQuiz.setRightComponent(jPanel_quizContent);

        javax.swing.GroupLayout jPanel_createQuizContentLayout = new javax.swing.GroupLayout(jPanel_createQuizContent);
        jPanel_createQuizContent.setLayout(jPanel_createQuizContentLayout);
        jPanel_createQuizContentLayout.setHorizontalGroup(
            jPanel_createQuizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane_CreateQuiz)
        );
        jPanel_createQuizContentLayout.setVerticalGroup(
            jPanel_createQuizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane_CreateQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel_createQuizLayout = new javax.swing.GroupLayout(jPanel_createQuiz);
        jPanel_createQuiz.setLayout(jPanel_createQuizLayout);
        jPanel_createQuizLayout.setHorizontalGroup(
            jPanel_createQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_createQuizContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_createQuizLayout.setVerticalGroup(
            jPanel_createQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_createQuizContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane_manageQuiz.addTab(bundle.getString("QuizingApp.jPanel_createQuiz.TabConstraints.tabTitle"), jPanel_createQuiz); // NOI18N

        jLabel_viewQuizSelectSubject.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_viewQuizSelectSubject.setForeground(new java.awt.Color(0, 102, 204));
        jLabel_viewQuizSelectSubject.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectSubject.text")); // NOI18N

        jComboBox_viewQuizSelectSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_viewQuizSelectTopic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_viewQuizSelectTopic.setForeground(new java.awt.Color(0, 102, 204));
        jLabel_viewQuizSelectTopic.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectTopic.text")); // NOI18N

        jComboBox_viewQuizSelectTopic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox_viewQuizSelectQuiz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_viewQuizSelectQuiz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_viewQuizSelectQuiz.setForeground(new java.awt.Color(0, 102, 204));
        jLabel_viewQuizSelectQuiz.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectQuiz.text")); // NOI18N

        jLabel_viewQuizQSolved.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_viewQuizQSolved.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_viewQuizQSolved.setText(bundle.getString("QuizingApp.jLabel_viewQuizQSolved.text")); // NOI18N

        jTextField__viewQuizQSolved.setEditable(false);
        jTextField__viewQuizQSolved.setText(bundle.getString("QuizingApp.jTextField__viewQuizQSolved.text")); // NOI18N

        jLabel_viewQuizTimeLeft.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel_viewQuizTimeLeft.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_viewQuizTimeLeft.setText(bundle.getString("QuizingApp.jLabel_viewQuizTimeLeft.text")); // NOI18N

        jTextField_viewQuizTimeLeft.setEditable(false);
        jTextField_viewQuizTimeLeft.setText(bundle.getString("QuizingApp.jTextField_viewQuizTimeLeft.text")); // NOI18N

        javax.swing.GroupLayout jPanel_quizTimerLayout = new javax.swing.GroupLayout(jPanel_quizTimer);
        jPanel_quizTimer.setLayout(jPanel_quizTimerLayout);
        jPanel_quizTimerLayout.setHorizontalGroup(
            jPanel_quizTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_quizTimerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_quizTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewQuizQSolved)
                    .addComponent(jLabel_viewQuizTimeLeft))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_quizTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_viewQuizTimeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jTextField__viewQuizQSolved))
                .addContainerGap())
        );
        jPanel_quizTimerLayout.setVerticalGroup(
            jPanel_quizTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_quizTimerLayout.createSequentialGroup()
                .addGroup(jPanel_quizTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField__viewQuizQSolved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_viewQuizQSolved))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_quizTimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_viewQuizTimeLeft)
                    .addComponent(jTextField_viewQuizTimeLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_selectQuizLayout = new javax.swing.GroupLayout(jPanel_selectQuiz);
        jPanel_selectQuiz.setLayout(jPanel_selectQuizLayout);
        jPanel_selectQuizLayout.setHorizontalGroup(
            jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewQuizSelectSubject)
                    .addComponent(jComboBox_viewQuizSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewQuizSelectTopic)
                    .addComponent(jComboBox_viewQuizSelectTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewQuizSelectQuiz)
                    .addComponent(jComboBox_viewQuizSelectQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_quizTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_selectQuizLayout.setVerticalGroup(
            jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_selectQuizLayout.createSequentialGroup()
                        .addGroup(jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_viewQuizSelectSubject)
                            .addComponent(jLabel_viewQuizSelectTopic)
                            .addComponent(jLabel_viewQuizSelectQuiz))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_selectQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_viewQuizSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_viewQuizSelectTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_viewQuizSelectQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel_quizTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel_selectQuizLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox_viewQuizSelectQuiz, jComboBox_viewQuizSelectSubject, jComboBox_viewQuizSelectTopic});

        jSplitPane_selectedQuizContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSplitPane_selectedQuizContent.setDividerLocation(200);

        jLabel_viewQuizQuestion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_viewQuizQuestion.setForeground(new java.awt.Color(0, 153, 51));
        jLabel_viewQuizQuestion.setText(bundle.getString("QuizingApp.jLabel_viewQuizQuestion.text")); // NOI18N

        jTextArea_viewQuizQuestion.setColumns(20);
        jTextArea_viewQuizQuestion.setLineWrap(true);
        jTextArea_viewQuizQuestion.setRows(5);
        jScrollPane_selectedQuizQuestion.setViewportView(jTextArea_viewQuizQuestion);

        jLabel_viewQuizQNo.setText(bundle.getString("QuizingApp.jLabel_viewQuizQNo.text")); // NOI18N

        javax.swing.GroupLayout jPanel_selectedQuizQuestionLayout = new javax.swing.GroupLayout(jPanel_selectedQuizQuestion);
        jPanel_selectedQuizQuestion.setLayout(jPanel_selectedQuizQuestionLayout);
        jPanel_selectedQuizQuestionLayout.setHorizontalGroup(
            jPanel_selectedQuizQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectedQuizQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_selectedQuizQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_selectedQuizQuestionLayout.createSequentialGroup()
                        .addComponent(jScrollPane_selectedQuizQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_selectedQuizQuestionLayout.createSequentialGroup()
                        .addComponent(jLabel_viewQuizQuestion)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel_viewQuizQNo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel_selectedQuizQuestionLayout.setVerticalGroup(
            jPanel_selectedQuizQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectedQuizQuestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_selectedQuizQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_viewQuizQuestion)
                    .addComponent(jLabel_viewQuizQNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_selectedQuizQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane_selectedQuizContent.setLeftComponent(jPanel_selectedQuizQuestion);

        jTable_selectedQuizOptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_selectedQuizOptions.setViewportView(jTable_selectedQuizOptions);

        javax.swing.GroupLayout jPanel_selectedQuizOptionsTableLayout = new javax.swing.GroupLayout(jPanel_selectedQuizOptionsTable);
        jPanel_selectedQuizOptionsTable.setLayout(jPanel_selectedQuizOptionsTableLayout);
        jPanel_selectedQuizOptionsTableLayout.setHorizontalGroup(
            jPanel_selectedQuizOptionsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_selectedQuizOptions)
        );
        jPanel_selectedQuizOptionsTableLayout.setVerticalGroup(
            jPanel_selectedQuizOptionsTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane_selectedQuizOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );

        jButton_viewQuizClear.setBackground(new java.awt.Color(255, 51, 51));
        jButton_viewQuizClear.setText(bundle.getString("QuizingApp.jButton_viewQuizClear.text")); // NOI18N

        jButton_viewQuizSubmit.setBackground(new java.awt.Color(0, 204, 102));
        jButton_viewQuizSubmit.setText(bundle.getString("QuizingApp.jButton_viewQuizSubmit.text")); // NOI18N

        jButton_viewQuizSave.setBackground(new java.awt.Color(0, 102, 204));
        jButton_viewQuizSave.setText(bundle.getString("QuizingApp.jButton_viewQuizSave.text")); // NOI18N

        jButton_viewQuizPrevious.setBackground(new java.awt.Color(102, 102, 102));
        jButton_viewQuizPrevious.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_viewQuizPrevious.setText(bundle.getString("QuizingApp.jButton_viewQuizPrevious.text")); // NOI18N

        jButton_viewQuizNext.setBackground(new java.awt.Color(102, 102, 102));
        jButton_viewQuizNext.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_viewQuizNext.setText(bundle.getString("QuizingApp.jButton_viewQuizNext.text")); // NOI18N

        javax.swing.GroupLayout jPanel_selectedQuizOptionsLayout = new javax.swing.GroupLayout(jPanel_selectedQuizOptions);
        jPanel_selectedQuizOptions.setLayout(jPanel_selectedQuizOptionsLayout);
        jPanel_selectedQuizOptionsLayout.setHorizontalGroup(
            jPanel_selectedQuizOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_selectedQuizOptionsTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_selectedQuizOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_viewQuizPrevious)
                .addGap(18, 18, 18)
                .addComponent(jButton_viewQuizClear)
                .addGap(18, 18, 18)
                .addComponent(jButton_viewQuizSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton_viewQuizSubmit)
                .addGap(18, 18, 18)
                .addComponent(jButton_viewQuizNext)
                .addContainerGap())
        );
        jPanel_selectedQuizOptionsLayout.setVerticalGroup(
            jPanel_selectedQuizOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectedQuizOptionsLayout.createSequentialGroup()
                .addComponent(jPanel_selectedQuizOptionsTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_selectedQuizOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_viewQuizSave)
                    .addComponent(jButton_viewQuizClear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_viewQuizSubmit)
                    .addComponent(jButton_viewQuizNext, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_viewQuizPrevious))
                .addContainerGap())
        );

        jPanel_selectedQuizOptionsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_viewQuizClear, jButton_viewQuizNext, jButton_viewQuizPrevious, jButton_viewQuizSave, jButton_viewQuizSubmit});

        jSplitPane_selectedQuizContent.setRightComponent(jPanel_selectedQuizOptions);

        javax.swing.GroupLayout jPanel_viewQuizContentLayout = new javax.swing.GroupLayout(jPanel_viewQuizContent);
        jPanel_viewQuizContent.setLayout(jPanel_viewQuizContentLayout);
        jPanel_viewQuizContentLayout.setHorizontalGroup(
            jPanel_viewQuizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_selectQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane_selectedQuizContent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel_viewQuizContentLayout.setVerticalGroup(
            jPanel_viewQuizContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewQuizContentLayout.createSequentialGroup()
                .addComponent(jPanel_selectQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane_selectedQuizContent, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_viewQuizLayout = new javax.swing.GroupLayout(jPanel_viewQuiz);
        jPanel_viewQuiz.setLayout(jPanel_viewQuizLayout);
        jPanel_viewQuizLayout.setHorizontalGroup(
            jPanel_viewQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_viewQuizContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_viewQuizLayout.setVerticalGroup(
            jPanel_viewQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_viewQuizContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane_manageQuiz.addTab(bundle.getString("QuizingApp.jPanel_viewQuiz.TabConstraints.tabTitle"), jPanel_viewQuiz); // NOI18N

        jLabel_viewQuizSelectSubject1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_viewQuizSelectSubject1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_viewQuizSelectSubject1.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectSubject1.text")); // NOI18N

        jComboBox_viewQuizSelectSubject1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_viewQuizSelectTopic1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_viewQuizSelectTopic1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_viewQuizSelectTopic1.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectTopic1.text")); // NOI18N

        jComboBox_viewQuizSelectTopic1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox_viewQuizSelectQuiz1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_viewQuizSelectQuiz1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_viewQuizSelectQuiz1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel_viewQuizSelectQuiz1.setText(bundle.getString("QuizingApp.jLabel_viewQuizSelectQuiz1.text")); // NOI18N

        javax.swing.GroupLayout jPanel_selectQuizSetLayout = new javax.swing.GroupLayout(jPanel_selectQuizSet);
        jPanel_selectQuizSet.setLayout(jPanel_selectQuizSetLayout);
        jPanel_selectQuizSetLayout.setHorizontalGroup(
            jPanel_selectQuizSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectQuizSetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_selectQuizSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_viewQuizSelectSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_viewQuizSelectSubject1))
                .addGap(35, 35, 35)
                .addGroup(jPanel_selectQuizSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewQuizSelectTopic1)
                    .addComponent(jComboBox_viewQuizSelectTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel_selectQuizSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_viewQuizSelectQuiz1)
                    .addComponent(jComboBox_viewQuizSelectQuiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_selectQuizSetLayout.setVerticalGroup(
            jPanel_selectQuizSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_selectQuizSetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_selectQuizSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_viewQuizSelectSubject1)
                    .addComponent(jLabel_viewQuizSelectTopic1)
                    .addComponent(jLabel_viewQuizSelectQuiz1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_selectQuizSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_viewQuizSelectTopic1)
                    .addGroup(jPanel_selectQuizSetLayout.createSequentialGroup()
                        .addComponent(jComboBox_viewQuizSelectSubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox_viewQuizSelectQuiz1))
                .addContainerGap())
        );

        jButton_viewScoreClearList.setBackground(new java.awt.Color(0, 153, 204));
        jButton_viewScoreClearList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_viewScoreClearList.setText(bundle.getString("QuizingApp.jButton_viewScoreClearList.text")); // NOI18N

        jButton_viewScoreSaveList.setBackground(new java.awt.Color(0, 204, 102));
        jButton_viewScoreSaveList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_viewScoreSaveList.setText(bundle.getString("QuizingApp.jButton_viewScoreSaveList.text")); // NOI18N

        javax.swing.GroupLayout jPanel_viewScoreButtonsLayout = new javax.swing.GroupLayout(jPanel_viewScoreButtons);
        jPanel_viewScoreButtons.setLayout(jPanel_viewScoreButtonsLayout);
        jPanel_viewScoreButtonsLayout.setHorizontalGroup(
            jPanel_viewScoreButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewScoreButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_viewScoreClearList, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_viewScoreSaveList)
                .addContainerGap())
        );

        jPanel_viewScoreButtonsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_viewScoreClearList, jButton_viewScoreSaveList});

        jPanel_viewScoreButtonsLayout.setVerticalGroup(
            jPanel_viewScoreButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewScoreButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_viewScoreClearList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_viewScoreSaveList))
        );

        jPanel_viewScoreButtonsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_viewScoreClearList, jButton_viewScoreSaveList});

        jTable_viewScores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_viewScoresContent.setViewportView(jTable_viewScores);

        javax.swing.GroupLayout jPanel_viewScoresLayout = new javax.swing.GroupLayout(jPanel_viewScores);
        jPanel_viewScores.setLayout(jPanel_viewScoresLayout);
        jPanel_viewScoresLayout.setHorizontalGroup(
            jPanel_viewScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_selectQuizSet, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addComponent(jScrollPane_viewScoresContent)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_viewScoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_viewScoreButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_viewScoresLayout.setVerticalGroup(
            jPanel_viewScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_viewScoresLayout.createSequentialGroup()
                .addComponent(jPanel_selectQuizSet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_viewScoresContent, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel_viewScoreButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane_manageQuiz.addTab(bundle.getString("QuizingApp.jPanel_viewScores.TabConstraints.tabTitle"), jPanel_viewScores); // NOI18N

        javax.swing.GroupLayout jPanel_manageQuizLayout = new javax.swing.GroupLayout(jPanel_manageQuiz);
        jPanel_manageQuiz.setLayout(jPanel_manageQuizLayout);
        jPanel_manageQuizLayout.setHorizontalGroup(
            jPanel_manageQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_manageQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel_manageQuizLayout.setVerticalGroup(
            jPanel_manageQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_manageQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane_quiziingApp.addTab(bundle.getString("QuizingApp.jPanel_manageQuiz.TabConstraints.tabTitle"), jPanel_manageQuiz); // NOI18N
        jPanel_manageQuiz.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jPanel_manageQuiz.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout jPanel_contentLayout = new javax.swing.GroupLayout(jPanel_content);
        jPanel_content.setLayout(jPanel_contentLayout);
        jPanel_contentLayout.setHorizontalGroup(
            jPanel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_quiziingApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel_contentLayout.setVerticalGroup(
            jPanel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_quiziingApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane_quiziingApp.getAccessibleContext().setAccessibleName(bundle.getString("QuizingApp.jTabbedPane_quiziingApp.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usernameKeyTyped
        if (!isLoggedIn) {
            jPasswordField_password.setEnabled(true);
            if (evt.getKeyChar() == '\n') {
                jPasswordField_password.requestFocus();
                jPasswordField_password.selectAll();
            }
        }
    }//GEN-LAST:event_jTextField_usernameKeyTyped

    private void jPasswordField_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_passwordMouseClicked
        if (!isLoggedIn) {
            jPasswordField_password.setEnabled(true);
            jPasswordField_password.requestFocus();
            jPasswordField_password.selectAll();
        }
    }//GEN-LAST:event_jPasswordField_passwordMouseClicked

    private void jPasswordField_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_passwordKeyTyped
        if (!isLoggedIn) {
            jToggleButton_login.setEnabled(true);
            if (evt.getKeyChar() == '\n') {
                jToggleButton_login.requestFocus();
            }
        }
    }//GEN-LAST:event_jPasswordField_passwordKeyTyped

    private void jToggleButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_loginActionPerformed
        login();
    }//GEN-LAST:event_jToggleButton_loginActionPerformed

    private void jTextField_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usernameMouseClicked
        if (!isLoggedIn) {
            jTextField_username.selectAll();
            jPasswordField_password.setEnabled(true);
        }
    }//GEN-LAST:event_jTextField_usernameMouseClicked

    private void jToggleButton_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButton_loginKeyPressed
        if (evt.getKeyChar() == '\n') {
            login();
        }
    }//GEN-LAST:event_jToggleButton_loginKeyPressed

    private void jTextField_createQuizSubjectKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_createQuizSubjectKeyTyped
        quizSubject = jTextField_createQuizSubject.getText().trim();
        if ((evt.getKeyChar() == '\n') && (!quizSubject.isEmpty())) {
            jTextField_createQuizChapterOrTopic.setEnabled(true);
            jTextField_createQuizChapterOrTopic.requestFocus();
        }
    }//GEN-LAST:event_jTextField_createQuizSubjectKeyTyped

    private void jTextField_createQuizChapterOrTopicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_createQuizChapterOrTopicKeyTyped
        quizTopic = jTextField_createQuizChapterOrTopic.getText().trim();
        if ((evt.getKeyChar() == '\n') && (!quizTopic.isEmpty())) {
            jTextField_createQuizSetTimeLimit.setEnabled(true);
            jTextField_createQuizSetTimeLimit.requestFocus();
        }
    }//GEN-LAST:event_jTextField_createQuizChapterOrTopicKeyTyped

    private void jTextField_createQuizSetTimeLimitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_createQuizSetTimeLimitKeyTyped
        quizTimeLimit = jTextField_createQuizSetTimeLimit.getText().trim();
        if (!quizTimeLimit.isEmpty()) {
            jButton_createQuizAddQuestion.setEnabled(true);
        }
        if (evt.getKeyChar() == '\n') {
            jButton_createQuizAddQuestion.requestFocus();
        }
    }//GEN-LAST:event_jTextField_createQuizSetTimeLimitKeyTyped

    private void jButton_createQuizAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createQuizAddQuestionActionPerformed
        jTextField_createQuizSubject.setEnabled(false);
        jTextField_createQuizChapterOrTopic.setEnabled(false);
        jTextField_createQuizSetTimeLimit.setEnabled(false);
        quizSubject = jTextField_createQuizSubject.getText().trim();
        quizTopic = jTextField_createQuizChapterOrTopic.getText().trim();
        quizTimeLimit = jTextField_createQuizSetTimeLimit.getText().trim();
        quiz.setSubject(quizSubject);
        quiz.setTopic(quizTopic);
        quiz.setTimeLimit(quizTimeLimit);
        jTextArea_createQuizQuestion.setEnabled(true);
        jTextArea_createQuizQuestion.requestFocus();
        jComboBox_createQuizDifficultyLevel.setEnabled(true);
    }//GEN-LAST:event_jButton_createQuizAddQuestionActionPerformed

    private void jTextArea_createQuizQuestionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_createQuizQuestionKeyTyped
        int count = 0;
        if (!jTextArea_createQuizQuestion.getText().trim().isEmpty()) {
            jButton_createQuizSave.setEnabled(true);
            jButton_selectImage.setEnabled(true);
            count = Integer.parseInt(jTextField_totalQuestions.getText());
            if (currentQuestionNumber > 0) {
                jButton_createQuizPrevious.setEnabled(true);
            }
            if (count > currentQuestionNumber) {
                jButton_createQuizNext.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTextArea_createQuizQuestionKeyTyped

    private void jButton_createQuizSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createQuizSaveActionPerformed
        String question = jTextArea_createQuizQuestion.getText().trim();
        int thisQuestion = Integer.parseInt(jTextField_totalQuestions.getText());
        int difficulty = Integer.parseInt(jComboBox_createQuizDifficultyLevel.getSelectedItem().toString());
        String image = null;
        if (currentQuestionNumber == 0) {
            currentQuestionNumber = thisQuestion + 1;
        } else {
            currentQuestionNumber++;
        }
        if (!question.isEmpty()) {
            if (image == null) {
//                questions = new Questions[currentQuestionNumber];
                questions[currentQuestionNumber - 1] = new Questions(currentQuestionNumber, difficulty, question);
            } else {
//                questions = new Questions[questionNumber];
                questions[currentQuestionNumber - 1] = new Questions(currentQuestionNumber, difficulty, question, image);
            }
            jTextField_totalQuestions.setText(String.valueOf(currentQuestionNumber));
        }
        jTextArea_createQuizQuestion.setText("");
        jTextArea_createQuizQuestion.requestFocus();
//        jButton_createQuizSave.setEnabled(false);
//        jButton_createQuizAddOption.setEnabled(true);
//        jButton_createQuizAddOption.requestFocus();
        //TEST
        System.out.println("");
        System.out.println("Question Number: " + questions[currentQuestionNumber - 1].getQuestionNo());
        System.out.println("Question Difficulty: " + questions[currentQuestionNumber - 1].getDifficulty());
        System.out.println("Question Text: " + questions[currentQuestionNumber - 1].getText());
        System.out.println("Question Image: " + questions[currentQuestionNumber - 1].getImage());
        System.out.println("Question UUID: " + questions[currentQuestionNumber - 1].getUuid());
        System.out.println("");
    }//GEN-LAST:event_jButton_createQuizSaveActionPerformed

    private void jButton_createQuizPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createQuizPreviousActionPerformed
        previousQuestionNumber = currentQuestionNumber - 1;
        currentQuestionNumber = previousQuestionNumber;
        jButton_createQuizNext.setEnabled(true);
        if (currentQuestionNumber == 1) {
            jButton_createQuizPrevious.setEnabled(false);
        }
        jTextArea_createQuizQuestion.setText(questions[currentQuestionNumber - 1].getText());
        jComboBox_createQuizDifficultyLevel.setSelectedIndex(questions[currentQuestionNumber - 1].getDifficulty());
        //TEST
        System.out.println("");
        System.out.println("Question Number: " + questions[currentQuestionNumber - 1].getQuestionNo());
        System.out.println("Question Difficulty: " + questions[currentQuestionNumber - 1].getDifficulty());
        System.out.println("Question Text: " + questions[currentQuestionNumber - 1].getText());
        System.out.println("Question Image: " + questions[currentQuestionNumber - 1].getImage());
        System.out.println("Question UUID: " + questions[currentQuestionNumber - 1].getUuid());
        System.out.println("");
    }//GEN-LAST:event_jButton_createQuizPreviousActionPerformed

    private void jButton_createQuizNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_createQuizNextActionPerformed
        nextQuestionNumber = currentQuestionNumber + 1;
        currentQuestionNumber = nextQuestionNumber;
        int totalQuestions = Integer.parseInt(jTextField_totalQuestions.getText());
        jButton_createQuizPrevious.setEnabled(true);
        if (currentQuestionNumber == totalQuestions) {
            jButton_createQuizNext.setEnabled(false);
        }
        jTextArea_createQuizQuestion.setText(questions[currentQuestionNumber - 1].getText());
        jComboBox_createQuizDifficultyLevel.setSelectedIndex(questions[currentQuestionNumber - 1].getDifficulty());
        //TEST
        System.out.println("");
        System.out.println("Question Number: " + questions[currentQuestionNumber - 1].getQuestionNo());
        System.out.println("Question Difficulty: " + questions[currentQuestionNumber - 1].getDifficulty());
        System.out.println("Question Text: " + questions[currentQuestionNumber - 1].getText());
        System.out.println("Question Image: " + questions[currentQuestionNumber - 1].getImage());
        System.out.println("Question UUID: " + questions[currentQuestionNumber - 1].getUuid());
        System.out.println("");
    }//GEN-LAST:event_jButton_createQuizNextActionPerformed

    private void jTextField_totalQuestionsCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_totalQuestionsCaretUpdate
        jComboBox_createQuizQNo.setEnabled(true);
        jComboBox_createQuizONo.setEnabled(true);
    }//GEN-LAST:event_jTextField_totalQuestionsCaretUpdate

    private void jComboBox_createQuizQNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_createQuizQNoActionPerformed
        try {
            int questionNo = Integer.parseInt(jComboBox_createQuizQNo.getSelectedItem().toString());
            jTextArea_createQuizQuestion.setText(questions[questionNo - 1].getText());
            jComboBox_createQuizDifficultyLevel.setSelectedIndex(questions[questionNo - 1].getDifficulty());
        } catch (Exception e) {
            jTextArea_createQuizQuestion.setText("No Quiz Found!!");
        }

    }//GEN-LAST:event_jComboBox_createQuizQNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            QuizingApp quizingApp = new QuizingApp();

            public void run() {
                //Set the Quiz Management Tab invisible
                quizingApp.jTabbedPane_manageQuiz.setVisible(false);
                quizingApp.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_createQuizAddOption;
    private javax.swing.JButton jButton_createQuizAddQuestion;
    private javax.swing.JButton jButton_createQuizNext;
    private javax.swing.JButton jButton_createQuizPrevious;
    private javax.swing.JButton jButton_createQuizSave;
    private javax.swing.JButton jButton_createQuizSubmitQuiz;
    private javax.swing.JButton jButton_selectImage;
    private javax.swing.JButton jButton_viewQuizClear;
    private javax.swing.JButton jButton_viewQuizNext;
    private javax.swing.JButton jButton_viewQuizPrevious;
    private javax.swing.JButton jButton_viewQuizSave;
    private javax.swing.JButton jButton_viewQuizSubmit;
    private javax.swing.JButton jButton_viewScoreClearList;
    private javax.swing.JButton jButton_viewScoreSaveList;
    private javax.swing.JCheckBox jCheckBox_createQuizSelectCorrectAnswer;
    private javax.swing.JComboBox jComboBox_createQuizDifficultyLevel;
    private javax.swing.JComboBox jComboBox_createQuizONo;
    private javax.swing.JComboBox jComboBox_createQuizQNo;
    private javax.swing.JComboBox jComboBox_viewQuizSelectQuiz;
    private javax.swing.JComboBox jComboBox_viewQuizSelectQuiz1;
    private javax.swing.JComboBox jComboBox_viewQuizSelectSubject;
    private javax.swing.JComboBox jComboBox_viewQuizSelectSubject1;
    private javax.swing.JComboBox jComboBox_viewQuizSelectTopic;
    private javax.swing.JComboBox jComboBox_viewQuizSelectTopic1;
    private javax.swing.JLabel jLabel_chapterOrTopic;
    private javax.swing.JLabel jLabel_createQuizDifficultyLevel;
    private javax.swing.JLabel jLabel_createQuizONo;
    private javax.swing.JLabel jLabel_createQuizQNo;
    private javax.swing.JLabel jLabel_createQuizSubject;
    private javax.swing.JLabel jLabel_header;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_questionOrOption;
    private javax.swing.JLabel jLabel_setTimeLimit;
    private javax.swing.JLabel jLabel_totalQuestions;
    private javax.swing.JLabel jLabel_userAccessStatus;
    private javax.swing.JLabel jLabel_userLogin;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JLabel jLabel_viewQuizQNo;
    private javax.swing.JLabel jLabel_viewQuizQSolved;
    private javax.swing.JLabel jLabel_viewQuizQuestion;
    private javax.swing.JLabel jLabel_viewQuizSelectQuiz;
    private javax.swing.JLabel jLabel_viewQuizSelectQuiz1;
    private javax.swing.JLabel jLabel_viewQuizSelectSubject;
    private javax.swing.JLabel jLabel_viewQuizSelectSubject1;
    private javax.swing.JLabel jLabel_viewQuizSelectTopic;
    private javax.swing.JLabel jLabel_viewQuizSelectTopic1;
    private javax.swing.JLabel jLabel_viewQuizTimeLeft;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_content;
    private javax.swing.JPanel jPanel_createQuiz;
    private javax.swing.JPanel jPanel_createQuizContent;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_manageQuiz;
    private javax.swing.JPanel jPanel_quizContent;
    private javax.swing.JPanel jPanel_quizDetails;
    private javax.swing.JPanel jPanel_quizImage;
    private javax.swing.JPanel jPanel_quizTimer;
    private javax.swing.JPanel jPanel_selectQuiz;
    private javax.swing.JPanel jPanel_selectQuizSet;
    private javax.swing.JPanel jPanel_selectedQuizOptions;
    private javax.swing.JPanel jPanel_selectedQuizOptionsTable;
    private javax.swing.JPanel jPanel_selectedQuizQuestion;
    private javax.swing.JPanel jPanel_userAccess;
    private javax.swing.JPanel jPanel_viewQuiz;
    private javax.swing.JPanel jPanel_viewQuizContent;
    private javax.swing.JPanel jPanel_viewScoreButtons;
    private javax.swing.JPanel jPanel_viewScores;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JScrollPane jScrollPane_quizImage;
    private javax.swing.JScrollPane jScrollPane_quizText;
    private javax.swing.JScrollPane jScrollPane_selectedQuizOptions;
    private javax.swing.JScrollPane jScrollPane_selectedQuizQuestion;
    private javax.swing.JScrollPane jScrollPane_viewScoresContent;
    private javax.swing.JSplitPane jSplitPane_CreateQuiz;
    private javax.swing.JSplitPane jSplitPane_selectedQuizContent;
    private javax.swing.JTabbedPane jTabbedPane_manageQuiz;
    private javax.swing.JTabbedPane jTabbedPane_quiziingApp;
    private javax.swing.JTable jTable_selectedQuizOptions;
    private javax.swing.JTable jTable_viewScores;
    private javax.swing.JTextArea jTextArea_createQuizQuestion;
    private javax.swing.JTextArea jTextArea_viewQuizQuestion;
    private javax.swing.JTextField jTextField__viewQuizQSolved;
    private javax.swing.JTextField jTextField_createQuizChapterOrTopic;
    private javax.swing.JTextField jTextField_createQuizSetTimeLimit;
    private javax.swing.JTextField jTextField_createQuizSubject;
    private javax.swing.JTextField jTextField_totalQuestions;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTextField jTextField_viewQuizTimeLeft;
    private javax.swing.JToggleButton jToggleButton_login;
    // End of variables declaration//GEN-END:variables

    private void login() {
        String username = jTextField_username.getText();
        String password = jPasswordField_password.getText();
        if (!isLoggedIn) {
            //login for normal users
            isLoggedIn = methods.login(username, password);
            //if login is successful
            if (isLoggedIn) {
                jToggleButton_login.setBackground(Color.RED);
                jToggleButton_login.setText("Logout");
                jTextField_username.setEnabled(false);
                jPasswordField_password.setEnabled(false);
                jTabbedPane_manageQuiz.setVisible(false);
                jLabel_userAccessStatus.setForeground(Color.BLACK);
                jLabel_userAccessStatus.setText("Successfully Logged In");
            } else {
                //try Admin login
                isLoggedIn = methods.loginAdmin(username, password);
                if (isLoggedIn) {
                    jToggleButton_login.setBackground(Color.RED);
                    jToggleButton_login.setText("Logout");
                    jTextField_username.setEnabled(false);
                    jPasswordField_password.setEnabled(false);
                    jTabbedPane_manageQuiz.setVisible(true);
                    jLabel_userAccessStatus.setForeground(Color.BLUE);
                    jLabel_userAccessStatus.setText("Admin login Successful");
                } else {
                    jLabel_userAccessStatus.setForeground(Color.RED);
                    jLabel_userAccessStatus.setText("Login Unsuccessful. Check user credentials");
                    jToggleButton_login.setSelected(false);
                }
            }
        } else {
            //logout
            isLoggedIn = !(methods.logout(username));
            //if logout is successful
            if (!isLoggedIn) {
                jToggleButton_login.setBackground(Color.GRAY);
                jToggleButton_login.setText("Login");
                jTextField_username.setEnabled(true);
                jPasswordField_password.setEnabled(true);
                jTabbedPane_manageQuiz.setVisible(false);
                jLabel_userAccessStatus.setText("");
            }
        }
    }
}
